sudo: required
language: generic

services:
    - docker

befere_install:
    - docker build -t 0xf0d0/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true 0xf0d0/docker-react yarn test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-440722146424"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY